-- Extend Game table with structured metadata for RAG and embeddings
ALTER TABLE "Game"
  ADD COLUMN IF NOT EXISTS "summary" VARCHAR(1500),
  ADD COLUMN IF NOT EXISTS "featureSummary" VARCHAR(2000),
  ADD COLUMN IF NOT EXISTS "genreTags" TEXT[] DEFAULT ARRAY[]::TEXT[] NOT NULL,
  ADD COLUMN IF NOT EXISTS "platformTags" TEXT[] DEFAULT ARRAY[]::TEXT[] NOT NULL,
  ADD COLUMN IF NOT EXISTS "gameplayTags" TEXT[] DEFAULT ARRAY[]::TEXT[] NOT NULL,
  ADD COLUMN IF NOT EXISTS "worldTags" TEXT[] DEFAULT ARRAY[]::TEXT[] NOT NULL,
  ADD COLUMN IF NOT EXISTS "visualStyleTags" TEXT[] DEFAULT ARRAY[]::TEXT[] NOT NULL,
  ADD COLUMN IF NOT EXISTS "monetization" VARCHAR(200),
  ADD COLUMN IF NOT EXISTS "idealFor" VARCHAR(500),
  ADD COLUMN IF NOT EXISTS "systemRequirements" JSONB,
  ADD COLUMN IF NOT EXISTS "ragProfile" JSONB,
  ADD COLUMN IF NOT EXISTS "sourceUrls" JSONB;
